module: Swiftarr
module_version: 0.1
title: Swiftarr - The v3 Twitarr server
author: The Twitarr Team
# author_url:
github_url: https://github.com/jocosocial/swiftarr
github_file_prefix: https://github.com/jocosocial/swiftarr/tree/master
# copyright:

swift_version: 5.7.2

theme: fullwidth
skip_undocumented: no
hide_documentation_coverage: no
# head:

documentation: docs/Swiftarr/*.md
abstract: docs/Swiftarr/Sections/*.md

min_acl: private

custom_categories:
  - name: Overview
    children:
      - Documentation
      - Contributing
      - Development
      - Roadmap
      - Special Files

  - name: Operations
    children:
      - Configuration
      - MacOS Installation
      - Linux Installation
      - Docker Installation
      - Database Migration

  - name: Twitarr API
    children:
      - Pitch
      - API Overview
      - Canonical Links
      - API Changelist

  - name: Controllers
    children:
    - AdminController
    - AlertController
    - AuthController
    - BoardgameController
    - ClientController
    - EventController
    - FezController
    - ForumController
    - ImageController
    - KaraokeController
    - ModerationController
    - PhonecallController
    - TestController
    - TwitarrController
    - UserController
    - UsersController

  - name: Models
    children:
    - AlertWord
    - Announcement
    - Boardgame
    - Category
    - DailyTheme
    - Event
    - FezPost
    - ForumEdit
    - ForumPostEdit
    - ForumPost
    - Forum
    - FriendlyFezEdit
    - FriendlyFez
    - KaraokePlayedSong
    - KaraokeSong
    - ModeratorAction
    - MuteWord
    - ProfileEdit
    - RegistrationCode
    - Report
    - TimeZoneChange
    - Token
    - TwarrtEdit
    - Twarrt
    - UserNote
    - UserRole
    - User
    
  - name: Enumerations
    children:
    - ContentModerationStatus
    - EventModification
    - EventType
    - ExportableFormat
    - FezType
    - GDError
    - ImageSizeGroup
    - ImageUsage
    - ImportableFormat
    - LikeType
    - ModeratorActionType
    - NotificationType
    - ReportType
    - SwiftarrClientApp
    - SwiftarrFeature
    - UserAccessLevel

  - name: Request Structs
    children:
    - AnnouncementCreateData
    - EventsUpdateData
    - FezContentData
    - ForumCreateData
    - ImageUploadData
    - NoteCreateData
    - PostContentData
    - ReportData
    - UserCreateData
    - UserPasswordData
    - UserRecoveryData
    - UserUsernameData
    - UserVerifyData
    
  - name: Return Structs
    children:
    - AddedUserData
    - AnnouncementData
    - BoardgameData
    - BoardgameResponseData
    - CategoryData
    - CreatedUserData
    - CurrentUserData
    - EventData
    - FezData
    - FezPostData
    - ForumData
    - ForumListData
    - NoteData
    - PostData
    - PostDetailData
    - ProfilePublicData
    - TokenStringData
    - TwarrtData
    - TwarrtDetailData
    - UserHeader
    - UserSearch
    
  - name: Extensions
    children:
    - Application
    - Array
    - Bool
    - CharacterSet
    - Collection
    - Comparable
    - Data
    - Date
    - Formatter
    - Foundation
    - ISO8601DateFormatter
    - JSONDecoder
    - JSONEncoder
    - Model
    - PathComponent
    - RedisClient
    - Request
    - SiblingsProperty
    - String
    - UUID
    
  - name: Migrations
    children:
      - CreateAdminUsers
      - CreateCategories
      - SetInitialCategoryForumCounts
      - CreateClientUsers
      - ImportBoardgames
      - SetInitialEventForums
      - ImportRegistrationCodes
      - ImportEvents
      - ImportKaraokeSongs
      - CreateForums
      - CreateCustomEnums
      - CreateTestUsers
      - CreateTestData

  - name: Pivots
    children:
    - PostLikes
    - TwarrtLikes
    
  - name: Protocols
    children:
    - APIRouteCollection
    - ContentFilterable
    - ExportableFormatter
    - FezProtocol
    - ImportableFormatter
    - LibGdExportableFormatter
    - LibGdImportableFormatter
    - LibGdParametrizableExportFormatter
    - RCFValidatable
    - Reportable
    - SiteControllerUtils
    - StoredSetting
    
  - name: Internal Structs/Classes
    children:
    - EventParser
    - Settings
    
