module: Swiftarr
module_version: 0.1
title: Swiftarr - The v3 Twitarr server
author: The Twitarr Team
# author_url:
github_url: https://github.com/jocosocial/swiftarr
github_file_prefix: https://github.com/jocosocial/swiftarr/tree/master
# copyright:

swift_version: 5.10.0

theme: fullwidth
skip_undocumented: no
hide_documentation_coverage: no
# head:

documentation: docs/Swiftarr/*.md
abstract: docs/Swiftarr/Sections/*.md

min_acl: private

# @TODO should we exclude some stuff?
#exclude:
#  - "Sources/swiftarr/Site*"
#  - "Sources/swiftarr/Migrations*"

custom_categories:
  - name: Overview
    children:
      - Documentation
      - Contributing
      - Development
      - Roadmap
      - Special Files
      - Release Calendar

  - name: Operations
    children:
      - Configuration
      - MacOS Installation
      - Linux Installation
      - Docker Installation
      - Database Migration

  - name: Twitarr API
    children:
      - Pitch
      - API Overview
      - Canonical Links
      - API Changelist
      - Example

  - name: Controllers
    children:
    - AdminController
    - AlertController
    - AuthController
    - BoardgameController
    - ClientController
    - EventController
    - FezController
    - ForumController
    - HuntController
    - ImageController
    - KaraokeController
    - MicroKaraokeController
    - ModerationController
    - PerformerController
    - PersonalEventController
    - PhonecallController
    - PhotostreamController
    - TestController
    - TwitarrController
    - UserController
    - UsersController

  - name: Models
    children:
    - AlertWord
    - Announcement
    - Boardgame
    - Category
    - DailyTheme
    - Event
    - FezPost
    - ForumEdit
    - ForumPostEdit
    - ForumPost
    - Forum
    - FriendlyFezEdit
    - FriendlyFez
    - Hunt
    - KaraokePlayedSong
    - KaraokeSong
    - ModeratorAction
    - MuteWord
    - ProfileEdit
    - Puzzle
    - RegistrationCode
    - Report
    - TimeZoneChange
    - Token
    - TwarrtEdit
    - Twarrt
    - UserNote
    - UserRole
    - User
    
  - name: Enumerations
    children:
    - CallInResult
    - ContentModerationStatus
    - EventModification
    - EventType
    - ExportableFormat
    - FezType
    - GDError
    - ImageSizeGroup
    - ImageUsage
    - ImportableFormat
    - LikeType
    - ModeratorActionType
    - NotificationType
    - ReportType
    - SwiftarrClientApp
    - SwiftarrFeature
    - UserAccessLevel
    - UserRoleType

  - name: Request Structs
    children:
    - AnnouncementCreateData
    - EventsUpdateData
    - FezContentData
    - ForumCreateData
    - ImageUploadData
    - NoteCreateData
    - PostContentData
    - ReportData
    - UserCreateData
    - UserPasswordData
    - UserRecoveryData
    - UserUsernameData
    - UserVerifyData
    
  - name: Return Structs
    children:
    - AddedUserData
    - AnnouncementData
    - BoardgameData
    - BoardgameResponseData
    - CategoryData
    - CreatedUserData
    - CurrentUserData
    - EventData
    - FezData
    - FezPostData
    - ForumData
    - ForumListData
    - HuntData
    - HuntListData
    - HuntPuzzleCallInResultData
    - HuntPuzzleDetailData
    - NoteData
    - PostData
    - PostDetailData
    - ProfilePublicData
    - TokenStringData
    - TwarrtData
    - TwarrtDetailData
    - UserHeader
    - UserSearch
    
  - name: Extensions
    children:
    - Application
    - Array
    - Bool
    - CharacterSet
    - Collection
    - Comparable
    - Data
    - Date
    - Formatter
    - Foundation
    - ISO8601DateFormatter
    - JSONDecoder
    - JSONEncoder
    - Model
    - PathComponent
    - QueryBuilder
    - RedisClient
    - Request
    - SiblingsProperty
    - String
    - Substring
    - UUID
    
  - name: Migrations
    children:
      - CreateAdminUsers
      - CreateAlertWordPivotSchema
      - CreateAlertWordSchema
      - CreateAnnouncementSchema
      - CreateBoardgameFavoriteSchema
      - CreateBoardgameSchema
      - CreateCategories
      - CreateCategorySchema
      - CreateClientUsers
      - CreateCustomEnums
      - CreateDailyThemeSchema
      - CreateEventFavoriteSchema
      - CreateEventSchema
      - CreateFezParticipantSchema
      - CreateFezPostSchema
      - CreateForumEditSchema
      - CreateForumPostEditSchema
      - CreateForumPostSchema
      - CreateForumReadersSchema
      - CreateForums
      - CreateForumSchema
      - CreateFriendlyFezEditSchema
      - CreateFriendlyFezSchema
      - CreateHuntSchema
      - CreateKaraokeFavoriteSchema
      - CreateKaraokePlayedSongSchema
      - CreateKaraokeSongSchema
      - CreateModeratorActionSchema
      - CreateMuteWordSchema
      - CreatePostLikesSchema
      - CreateProfileEditSchema
      - CreatePuzzleCallInSchema
      - CreatePuzzleSchema
      - CreateRegistrationCodeSchema
      - CreateReportSchema
      - CreateTestData
      - CreateTestUsers
      - CreateTimeZoneChangeSchema
      - CreateTokenSchema
      - CreateTwarrtEditSchema
      - CreateTwarrtLikesSchema
      - CreateTwarrtSchema
      - CreateUserFavoriteSchema
      - CreateUserNoteSchema
      - CreateUserRoleSchema
      - CreateUserSchema
      - ImportBoardgames
      - ImportEvents
      - ImportKaraokeSongs
      - ImportRegistrationCodes
      - SetInitialCategoryForumCounts
      - SetInitialEventForums
      - UpdateForumReadersLastPostReadSchema
      - UpdateForumReadersMuteSchema

  - name: Pivots
    children:
    - AlertWordPivot
    - BoardgameFavorite
    - EventFavorite
    - FezParticipant
    - ForumReaders
    - KaraokeFavorite
    - PostLikes
    - PuzzleCallIn
    - TwarrtLikes
    - UserFavorite
    
  - name: Protocols
    children:
    - APIRouteCollection
    - ContentFilterable
    - ExportableFormatter
    - FezProtocol
    - ImportableFormatter
    - LibGdExportableFormatter
    - LibGdImportableFormatter
    - LibGdParametrizableExportFormatter
    - RCFValidatable
    - Reportable
    - Searchable
    - SiteControllerUtils
    - StoredSetting
    
  - name: Internal Structs/Classes
    children:
    - EventParser
    - Settings

  - name: Site Controllers
    children:
      - SiteAdminController
      - SiteBoardgameController
      - SiteController
      - SiteEventsController
      - SiteFileController
      - SiteForumController
      - SiteFriendlyFezController
      - SiteHuntController
      - SiteKaraokeController
      - SiteLoginController
      - SiteModController
      - SitePerformerController
      - SitePhotostreamController
      - SitePrivateEventController
      - SiteSeamailController
      - SiteTwitarrController
      - SiteUserController

  - name: Middleware
    children:
      - SwiftarrErrorMiddleware
      - CalendarSessionFixerMiddleware
      - DisabledAPISectionMiddleware
      - DisabledSiteSectionMiddleware
      - MinUserAccessLevelMiddleware
      - NotificationsMiddleware
      - RequireAdminMiddleware
      - RequireModeratorMiddleware
      - RequireTHOMiddleware
      - RequireTwitarrTeamMiddleware
      - RequireVerifiedMiddleware
      - SiteErrorMiddleware
      - SiteMinUserAccessLevelMiddleware
      - SiteNoRouteErrorMiddleware
      - SiteRequireAdminMiddleware
      - SiteRequireModeratorMiddleware
      - SiteRequireTHOMiddleware
      - SiteRequireTwitarrTeamMiddleware
      - SiteRequireVerifiedMiddleware
