services:
  postgres:
    image: docker.io/library/postgres:15
    user: postgres
    env_file:
      - "../Sources/swiftarr/seeds/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432

  redis:
    image: docker.io/library/redis:7
    user: redis
    env_file:
      - "../Sources/swiftarr/seeds/Private Swiftarr Config/${ENVIRONMENT}.env"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    ports:
      - ${REDIS_PORT}:6379

  web:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        # We always build the image in production mode.
        env: production
        port: ${SWIFTARR_PORT}
    ports:
      - ${SWIFTARR_PORT}:${SWIFTARR_PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - "../Sources/swiftarr/seeds/Private Swiftarr Config/${ENVIRONMENT}.env"
    volumes:
      - "../Sources/swiftarr/seeds:/app/swiftarr_swiftarr.resources/seeds:ro"
      - images:/app/images

volumes:
  images:
  pgdata:
  redisdata:
