FROM swift:5.6-bionic

RUN apt-get -qq update && apt-get install -y \
    libssl-dev zlib1g-dev libgd-dev \
    && rm -r /var/lib/apt/lists/*

WORKDIR /swiftarr
COPY . .

# Something goes wrong with this image when trying to use a different user.
# Blows up with the package cache config. As such we cannot become not-root.

RUN swift package resolve
RUN swift package clean

CMD ["swift", "test"]
