FROM swift:latest

RUN apt-get -qq update && apt-get install -y \
    libssl-dev zlib1g-dev \
    && rm -r /var/lib/apt/lists/*

WORKDIR /swiftarr
COPY . .

RUN swift package resolve
RUN swift package clean

CMD ["swift", "test"]
